# Generated by Django 5.2.3 on 2026-03-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_public_sales_contact',
            field=models.BooleanField(default=False, verbose_name='contato comercial publico'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='whatsapp'),
        ),
    ]
