# Generated by Django 5.2.3 on 2026-03-22 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=180, verbose_name='nome completo')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('birth_date', models.DateField(verbose_name='data de nascimento')),
                ('sex', models.CharField(choices=[('female', 'Feminino'), ('male', 'Masculino')], max_length=10, verbose_name='sexo biologico')),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='altura (cm)')),
                ('objective', models.CharField(blank=True, max_length=255, verbose_name='objetivo')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='tenants.tenant')),
            ],
            options={
                'ordering': ('full_name',),
                'unique_together': {('tenant', 'full_name', 'birth_date')},
            },
        ),
    ]
