# Generated by Django 5.2.3 on 2026-03-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=30, verbose_name='telefone')),
                ('company_name', models.CharField(blank=True, max_length=150, verbose_name='empresa')),
                ('plan_interest', models.CharField(choices=[('start', 'Start'), ('pro', 'Pro'), ('team', 'Team'), ('enterprise', 'Enterprise')], max_length=30, verbose_name='plano de interesse')),
                ('message', models.TextField(blank=True, verbose_name='mensagem')),
                ('status', models.CharField(choices=[('new', 'Novo'), ('contacted', 'Contatado'), ('qualified', 'Qualificado'), ('closed', 'Fechado')], default='new', max_length=20, verbose_name='status')),
            ],
            options={
                'verbose_name': 'lead publico',
                'verbose_name_plural': 'leads publicos',
                'ordering': ('-created_at',),
            },
        ),
    ]
