# Generated by Django 5.2.3 on 2026-03-22 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_at', models.DateField(verbose_name='data da avaliacao')),
                ('age', models.PositiveIntegerField(verbose_name='idade')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='peso (kg)')),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='altura (cm)')),
                ('target_fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='meta de gordura (%)')),
                ('protocol', models.CharField(choices=[('jackson_pollock', 'Jackson & Pollock'), ('faulkner', 'Faulkner'), ('custom', 'Personalizado')], default='jackson_pollock', max_length=40, verbose_name='protocolo')),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='cintura (cm)')),
                ('hip_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='quadril (cm)')),
                ('chest_skinfold_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='dobra peitoral (mm)')),
                ('abdomen_skinfold_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='dobra abdominal (mm)')),
                ('thigh_skinfold_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='dobra coxa (mm)')),
                ('tricep_skinfold_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='dobra triceps (mm)')),
                ('suprailiac_skinfold_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='dobra supra-iliaca (mm)')),
                ('humerus_diameter_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='diametro do umero (cm)')),
                ('femur_diameter_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='diametro do femur (cm)')),
                ('arm_circumference_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='perimetro braco (cm)')),
                ('thigh_circumference_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='perimetro coxa (cm)')),
                ('pushups_reps', models.PositiveIntegerField(blank=True, null=True, verbose_name='flexoes')),
                ('plank_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='prancha (s)')),
                ('cooper_distance_m', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cooper 12min (m)')),
                ('observations', models.TextField(blank=True, verbose_name='observacoes')),
                ('bmi', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bmi_classification', models.CharField(blank=True, max_length=50)),
                ('waist_hip_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('body_fat_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fat_mass_kg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('lean_mass_kg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ideal_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_assessments', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_assessments', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-assessed_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PosturalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_at', models.DateField(verbose_name='data da avaliacao')),
                ('lateral_view', models.TextField(blank=True, verbose_name='vista lateral')),
                ('anterior_view', models.TextField(blank=True, verbose_name='vista anterior')),
                ('posterior_view', models.TextField(blank=True, verbose_name='vista posterior')),
                ('markings', models.TextField(blank=True, verbose_name='marcacoes')),
                ('observations', models.TextField(blank=True, verbose_name='observacoes')),
                ('photo_upload_ready', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postural_assessments', to='students.student')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postural_assessments', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-assessed_at', '-created_at'),
            },
        ),
    ]
