# Generated by Django 5.2.3 on 2026-03-22 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('contact_name', models.CharField(max_length=150, verbose_name='responsavel')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('plan', models.CharField(choices=[('start', 'Start'), ('pro', 'Pro'), ('team', 'Team'), ('enterprise', 'Enterprise')], default='start', max_length=20, verbose_name='plano')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('notes', models.TextField(blank=True, verbose_name='observacoes')),
                ('primary_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_tenants', to=settings.AUTH_USER_MODEL, verbose_name='administrador inicial')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('tenant__name', 'user__username'),
                'unique_together': {('tenant', 'user')},
            },
        ),
    ]
